### ISSUE TITLE
IDE errors when compiling

### ISSUE THREAD

**Issue by weeblebiker** [collin80/ESP32RET#22]
Hi Collin,
I'm trying to get a A0 going recently purchased from SparkFun(believe it or not).

This is a A0 Rev2 dated 4/8/21 according to the schematics, it has WROVER-E  processor and a WS2812B addressable RGB on I/O 2.

I have selected board ESP32 Dev Module in IDE per A0's page.

I am trying the ESP32RET.ino directly with Arduino IDE2.0.3 I uploaded the master.ZIP file to the arduino library as usual.
I am getting a lot of errors when I try to compile, mostly c:\Users\david\Documents\Arduino\libraries\ESP32RET-master\wifi_manager.cpp,,,,,,ARDUINO_EVENT_WIFI_STA_DISCONNECTED,,,etc variations

why isn't it compiling?

**Comment by collin80** [comment]
I was aware that someone found a few A0's and sold them recently. Apparently you were one of few who were able to snap them up. 

I believe you've got the wrong version of Arduino-esp32 installed. The most recent versions of esp32ret expect a recent version of arduino-esp32 as well. They changed some wifi event names. So, either your esp32ret version is too new for your arduino-esp32 or your esp32ret version is too old for your arduino-esp32. Unfortunately I don't remember which one had ARDUINO_EVENT_WIFI_STA_DISCONNECTED. But, what I do know is that the version of esp32ret found at github will compile with the newest version of arduino-esp32 also found on github. So, updating them both to the newest version does work. Though, I don't remember if this is mentioned anywhere (I'll check and make sure to mention it in README.md if not) but ESP32RET is too large for the default partitioning scheme. You need to select "Minimal SPIFFS" to get it to compile and upload.
