### ISSUE TITLE
Running on ESP32 Devboard?

### ISSUE THREAD

**Issue by jameswarner62** [collin80/ESP32RET#3]
Struggling to get this working on an ESP32 devkitC - has it been tested on this?

**Comment by collin80** [comment]
I'm not sure but I believe it has. I use the actual EVTV boards but I compile as the ESP32 devkit so you'd think it would work. Perhaps recheck that you have everything connected to the proper pins. It's easy to make a mistake or wrong assumption there.

**Comment by jameswarner62** [comment]
Thanks - will keep at it then

**Comment by jameswarner62** [comment]
Found the issue for any other attempting this -  the USB>serial transceiver on the devboard does not support 1000000 baud - moving it back to 115200 in code and using savvycan via wifi works fine

**Comment by EdKok** [comment]
Old, I know. But does anyone know where to change this in code?
